# Generated by Django 2.2.2 on 2021-05-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
    ]
